import type { SigCode } from './types'

export const sigCodeSource = {
  name: 'User-provided SIG code sheets',
  reviewedAt: '2026-06-14',
}

export const sigCodes: SigCode[] = [
  { id: 'pc-after-meals', code: 'PC', meaning: 'After Meals', category: 'Timing' },
  { id: 'apl-applicatorful', code: 'APL', meaning: 'Applicatorful', category: 'Measurement' },
  { id: 'app-apply', code: 'APP', meaning: 'Apply', category: 'Application' },
  { id: 'ar-arthritis', code: 'AR', meaning: 'Arthritis', category: 'Symptom' },
  { id: 'ud-as-directed', code: 'UD', meaning: 'As Directed', category: 'Direction' },
  { id: 'hs-at-bedtime', code: 'HS', meaning: 'At Bedtime', category: 'Timing' },
  { id: 'stat-at-once', code: 'STAT', meaning: 'At Once', category: 'Timing' },
  { id: 'bp-blood-pressure', code: 'BP', meaning: 'Blood Pressure', category: 'Symptom' },
  { id: 'ac-before-meals', code: 'AC', meaning: 'Before Meals', category: 'Timing' },
  { id: 'bm-bowel-movement', code: 'BM', meaning: 'Bowel Movement', category: 'Symptom' },
  { id: 'po-by-mouth', code: 'PO', meaning: 'By Mouth', category: 'Route' },
  { id: 'cap-capsule', code: 'CAP', meaning: 'Capsule', category: 'Dosage Form' },
  { id: 'caps-capsules', code: 'CAPS', meaning: 'Capsules', category: 'Dosage Form' },
  { id: 'ci-circulation', code: 'CI', meaning: 'Circulation', category: 'Symptom' },
  { id: 'con-constipation', code: 'CON', meaning: 'Constipation', category: 'Symptom' },
  { id: 'medcp-consultation-provided-by', code: 'MEDCP', meaning: 'Consultation Provided By', category: 'Administration' },
  { id: 'cr-crush', code: 'CR', meaning: 'Crush', category: 'Administration' },
  { id: 'dy-daily', code: 'DY', meaning: 'Daily', category: 'Frequency' },
  { id: 'd-day', code: 'D', meaning: 'Day', category: 'Timing' },
  { id: 'ds-days', code: 'DS', meaning: 'Days', category: 'Timing' },
  { id: 'di-diarrhea', code: 'DI', meaning: 'Diarrhea', category: 'Symptom' },
  { id: 'dr-drink', code: 'DR', meaning: 'Drink', category: 'Administration' },
  { id: 'gtt-drop', code: 'GTT', meaning: 'Drop', category: 'Dosage Form' },
  { id: 'gtts-drops', code: 'GTTS', meaning: 'Drops', category: 'Dosage Form' },
  { id: 'qd-each-day', code: 'QD', meaning: 'Each Day', category: 'Frequency' },
  { id: 'qpm-each-evening', code: 'QPM', meaning: 'Each Evening', category: 'Timing' },
  { id: 'qam-each-morning', code: 'QAM', meaning: 'Each Morning', category: 'Timing' },
  { id: 'q-every', code: 'Q', meaning: 'Every', category: 'Frequency' },
  { id: 'q1h-every-hour', code: 'Q1H', meaning: 'Every Hour', category: 'Frequency' },
  { id: 'q2d-every-second-day', code: 'Q2D', meaning: 'Every Second Day', category: 'Frequency' },
  { id: 'q2h-every-2-hours', code: 'Q2H', meaning: 'Every 2 Hours', category: 'Frequency' },
  { id: 'q3h-every-3-hours', code: 'Q3H', meaning: 'Every 3 Hours', category: 'Frequency' },
  { id: 'q4h-every-4-hours', code: 'Q4H', meaning: 'Every 4 Hours', category: 'Frequency' },
  { id: 'q6h-every-6-hours', code: 'Q6H', meaning: 'Every 6 Hours', category: 'Frequency' },
  { id: 'q8h-every-8-hours', code: 'Q8H', meaning: 'Every 8 Hours', category: 'Frequency' },
  { id: 'q12h-every-12-hours', code: 'Q12H', meaning: 'Every 12 Hours', category: 'Frequency' },
  { id: 'q2-3h-every-2-3-hours', code: 'Q2-3H', meaning: 'Every 2-3 Hours', category: 'Frequency' },
  { id: 'q2-4h-every-2-4-hours', code: 'Q2-4H', meaning: 'Every 2-4 Hours', category: 'Frequency' },
  { id: 'q4-6h-every-4-6-hours', code: 'Q4-6H', meaning: 'Every 4-6 Hours', category: 'Frequency' },
  { id: 'fe-fever', code: 'FE', meaning: 'Fever', category: 'Symptom' },
  { id: 'fl-fluids', code: 'FL', meaning: 'Fluids', category: 'Administration' },
  { id: 'f-for', code: 'F', meaning: 'For', category: 'Direction' },
  { id: 'qid-four-times-daily', code: 'QID', meaning: 'Four Times Daily', category: 'Frequency' },
  { id: 'g-give', code: 'G', meaning: 'Give', category: 'Administration' },
  { id: 'hd-headache', code: 'HD', meaning: 'Headache', category: 'Symptom' },
  { id: 'hr-heart', code: 'HR', meaning: 'Heart', category: 'Symptom' },
  { id: 'h-hour', code: 'H', meaning: 'Hour', category: 'Timing' },
  { id: 'hrs-hours', code: 'HRS', meaning: 'Hours', category: 'Timing' },
  { id: 'au-in-each-ear', code: 'AU', meaning: 'In Each Ear', category: 'Route' },
  { id: 'ou-in-each-eye', code: 'OU', meaning: 'In Each Eye', category: 'Route' },
  { id: 'ien-in-each-nostril', code: 'IEN', meaning: 'In Each Nostril', category: 'Route' },
  { id: 'al-in-the-left-ear', code: 'AL', meaning: 'In the Left Ear', category: 'Route' },
  { id: 'ad-in-the-right-ear', code: 'AD', meaning: 'In the Right Ear', category: 'Route' },
  { id: 'os-in-the-left-eye', code: 'OS', meaning: 'In the Left Eye', category: 'Route' },
  { id: 'od-in-the-right-eye', code: 'OD', meaning: 'In the Right Eye', category: 'Route' },
  { id: 'inf-inflammation', code: 'INF', meaning: 'Inflammation', category: 'Symptom' },
  { id: 'i-inhale', code: 'I', meaning: 'Inhale', category: 'Route' },
  { id: 'inj-inject', code: 'INJ', meaning: 'Inject', category: 'Route' },
  { id: 'medap-injection-administered-by-pharmacist', code: 'MEDAP', meaning: 'Injection Administered by Pharmacist', category: 'Administration' },
  { id: 'ir-insert', code: 'IR', meaning: 'Insert', category: 'Administration' },
  { id: 'ins-instill', code: 'INS', meaning: 'Instill', category: 'Administration' },
  { id: 'r-into-the-rectum', code: 'R', meaning: 'Into the Rectum', category: 'Route' },
  { id: 'v-into-the-vagina', code: 'V', meaning: 'Into the Vagina', category: 'Route' },
  { id: 'ju-juice', code: 'JU', meaning: 'Juice', category: 'Administration' },
  { id: 'n-night', code: 'N', meaning: 'Night', category: 'Timing' },
  { id: 'ss-one-half', code: 'SS', meaning: 'One Half', category: 'Measurement' },
  { id: 'qbid-one-or-two-times-daily', code: 'QBID', meaning: 'One or Two Times Daily', category: 'Frequency' },
  { id: 'pa-pain', code: 'PA', meaning: 'Pain', category: 'Symptom' },
  { id: 'pl-place', code: 'PL', meaning: 'Place', category: 'Application' },
  { id: 'pf-puffs', code: 'PF', meaning: 'Puffs', category: 'Dosage Form' },
  { id: 'ra-rash', code: 'RA', meaning: 'Rash', category: 'Symptom' },
  { id: 'medra-refer-to-adaptation-form', code: 'MEDRA', meaning: 'Refer to Adaptation Form', category: 'Administration' },
  { id: 'medro-refer-to-opinions-form', code: 'MEDRO', meaning: 'Refer to Opinions Form', category: 'Administration' },
  { id: 'sw-shake-well', code: 'SW', meaning: 'Shake Well', category: 'Administration' },
  { id: 'sb-shortness-of-breath', code: 'SB', meaning: 'Shortness of Breath', category: 'Symptom' },
  { id: 'sp-sparingly', code: 'SP', meaning: 'Sparingly', category: 'Direction' },
  { id: 'supp-suppository', code: 'SUPP', meaning: 'Suppository', category: 'Dosage Form' },
  { id: 'tbl-tablespoon', code: 'TBL', meaning: 'Tablespoon', category: 'Measurement' },
  { id: 'tbls-tablespoonfuls', code: 'TBLS', meaning: 'Tablespoonfuls', category: 'Measurement' },
  { id: 'tab-tablet', code: 'TAB', meaning: 'Tablet', category: 'Dosage Form' },
  { id: 'tabs-tablets', code: 'TABS', meaning: 'Tablets', category: 'Dosage Form' },
  { id: 't-take', code: 'T', meaning: 'Take', category: 'Administration' },
  { id: 'tsp-teaspoon', code: 'TSP', meaning: 'Teaspoon', category: 'Measurement' },
  { id: 'tsps-teaspoonfuls', code: 'TSPS', meaning: 'Teaspoonfuls', category: 'Measurement' },
  { id: 'tqid-three-or-four-times-daily', code: 'TQID', meaning: 'Three or Four Times Daily', category: 'Frequency' },
  { id: 'tid-three-times-daily', code: 'TID', meaning: 'Three Times Daily', category: 'Frequency' },
  { id: 'btid-two-or-three-times-daily', code: 'BTID', meaning: 'Two or Three Times Daily', category: 'Frequency' },
  { id: 'admx-to-a-maximum-of', code: 'ADMX', meaning: 'To a Maximum of', category: 'Direction' },
  { id: 'aa-to-affected-area', code: 'AA', meaning: 'To Affected Area', category: 'Application' },
  { id: 'bid-twice-daily', code: 'BID', meaning: 'Twice Daily', category: 'Frequency' },
  { id: 'sl-under-the-tongue', code: 'SL', meaning: 'Under the Tongue', category: 'Route' },
  { id: 'uf-until-finished', code: 'UF', meaning: 'Until Finished', category: 'Direction' },
  { id: 'aq-water', code: 'AQ', meaning: 'Water', category: 'Administration' },
  { id: 'prn-when-required', code: 'PRN', meaning: 'When Required', category: 'Timing' },
  { id: 'prnf-when-necessary-for', code: 'PRNF', meaning: 'When Necessary For', category: 'Timing' },
  { id: 'c-with', code: 'C', meaning: 'With', category: 'Direction' },
  { id: 'cf-with-food', code: 'CF', meaning: 'With Food', category: 'Timing' },
  { id: 'cc-with-meals', code: 'CC', meaning: 'With Meals', category: 'Timing' },
  { id: 's-without', code: 'S', meaning: 'Without', category: 'Direction' },
  { id: 'aaa-apply-to-affected-area', code: 'AAA', meaning: 'Apply To Affected Area', category: 'Application' },
  { id: 'am-morning', code: 'AM', meaning: 'Morning; In The Morning; Before Noon', category: 'Timing' },
  { id: 'amp-ampule', code: 'AMP', meaning: 'Ampule Or Ampul', category: 'Dosage Form' },
  { id: 'apap-acetaminophen', code: 'APAP', meaning: 'Acetaminophen', category: 'Drug Name' },
  { id: 'as-left-ear', code: 'AS', meaning: 'Left Ear', category: 'Route' },
  { id: 'aud-apply-as-directed', code: 'AUD', meaning: 'Apply As Directed', category: 'Direction' },
  { id: 'bot-bottle', code: 'BOT', meaning: 'Bottle', category: 'Dosage Form' },
  { id: 'cm-centimeter', code: 'CM', meaning: 'Centimeter', category: 'Unit' },
  { id: 'cpm-chlorpheniramine', code: 'CPM', meaning: 'Chlorpheniramine', category: 'Drug Name' },
  { id: 'cre-cream', code: 'CRE', meaning: 'Cream', category: 'Dosage Form' },
  { id: 'd-c-discontinue', code: 'D/C', meaning: 'Discontinue', category: 'Direction' },
  { id: 'da-delayed-action', code: 'DA', meaning: 'Delayed Action', category: 'Dosage Form' },
  { id: 'daw-dispense-as-written', code: 'DAW', meaning: 'Dispense As Written', category: 'Direction' },
  { id: 'dc-diagnosis-code', code: 'DC', meaning: 'Diagnosis Code', category: 'Medical Term' },
  { id: 'dil-dilute-or-dissolve', code: 'DIL', meaning: 'Dilute Or Dissolve', category: 'Administration' },
  { id: 'disp-dispense', code: 'DISP', meaning: 'Dispense', category: 'Direction' },
  { id: 'dl-deciliter', code: 'DL', meaning: 'Deciliter', category: 'Unit' },
  { id: 'dm-dextromethorphan', code: 'DM', meaning: 'Dextromethorphan', category: 'Drug Name' },
  { id: 'dv-daily-value', code: 'DV', meaning: 'Daily Value', category: 'Measurement' },
  { id: 'ec-enteric-coated', code: 'EC', meaning: 'Enteric Coated', category: 'Dosage Form' },
  { id: 'ect-enteric-coated-tablet', code: 'ECT', meaning: 'Enteric-Coated Tablet', category: 'Dosage Form' },
  { id: 'er-extended-release-formulation', code: 'ER', meaning: 'Extended-Release Formulation', category: 'Dosage Form' },
  { id: 'fl-oz-fluid-ounce', code: 'FL OZ', meaning: 'Fluid Ounce', category: 'Unit' },
  { id: 'ft-foot-or-feet', code: 'FT', meaning: 'Foot Or Feet', category: 'Unit' },
  { id: 'gal-gallon', code: 'GAL', meaning: 'Gallon', category: 'Unit' },
  { id: 'gg-guaifenesin', code: 'GG', meaning: 'Guaifenesin', category: 'Drug Name' },
  { id: 'ggpe-guaifenesin-phenylephrine', code: 'GGPE', meaning: 'Guaifenesin/Phenylephrine', category: 'Drug Name' },
  { id: 'gm-gram', code: 'GM', meaning: 'Gram', category: 'Unit' },
  { id: 'gr-grain', code: 'GR', meaning: 'Grain', category: 'Unit' },
  { id: 'h2o-water', code: 'H2O', meaning: 'Water (H2O)', category: 'Administration' },
  { id: 'ha-headache', code: 'HA', meaning: 'Headache Symptom', category: 'Symptom' },
  { id: 'hbp-high-blood-pressure', code: 'HBP', meaning: 'High Blood Pressure', category: 'Symptom' },
  { id: 'hc-hydrocodone-or-hydrocortisone', code: 'HC', meaning: 'Hydrocodone Or Hydrocortisone', category: 'Drug Name' },
  { id: 'hct-hydrochlorothiazide', code: 'HCT', meaning: 'Hydrochlorothiazide', category: 'Drug Name' },
  { id: 'hctz-hydrochlorothiazide', code: 'HCTZ', meaning: 'Hydrochlorothiazide', category: 'Drug Name' },
  { id: 'htn-hypertension', code: 'HTN', meaning: 'Hypertension', category: 'Symptom' },
  { id: 'im-intramuscular', code: 'IM', meaning: 'Intramuscular', category: 'Route' },
  { id: 'in-inch', code: 'IN', meaning: 'Inch', category: 'Unit' },
  { id: 'inh-inhalation', code: 'INH', meaning: 'Inhalation', category: 'Route' },
  { id: 'itch-itching', code: 'ITCH', meaning: 'Itching', category: 'Symptom' },
  { id: 'iu-international-unit', code: 'IU', meaning: 'International Unit', category: 'Unit' },
  { id: 'iv-intravenous', code: 'IV', meaning: 'Intravenous', category: 'Route' },
  { id: 'k-potassium', code: 'K', meaning: 'Potassium', category: 'Drug Name' },
  { id: 'kcl-potassium-chloride', code: 'KCL', meaning: 'Potassium Chloride', category: 'Drug Name' },
  { id: 'kg-kilogram', code: 'KG', meaning: 'Kilogram', category: 'Unit' },
  { id: 'l-liter', code: 'L', meaning: 'Liter', category: 'Unit' },
  { id: 'la-long-acting', code: 'LA', meaning: 'Long-Acting', category: 'Dosage Form' },
  { id: 'lb-pound', code: 'LB', meaning: 'Pound', category: 'Unit' },
  { id: 'liq-liquid', code: 'LIQ', meaning: 'Liquid', category: 'Dosage Form' },
  { id: 'lot-lotion', code: 'LOT', meaning: 'Lotion', category: 'Dosage Form' },
  { id: 'm-meter', code: 'M', meaning: 'Meter', category: 'Unit' },
  { id: 'm2-square-meters', code: 'M2', meaning: 'Square Meters', category: 'Unit' },
  { id: 'mcg-microgram', code: 'MCG', meaning: 'Microgram', category: 'Unit' },
  { id: 'mcl-microliter', code: 'MCL', meaning: 'Microliter', category: 'Unit' },
  { id: 'mdi-metered-dose-inhaler', code: 'MDI', meaning: 'Metered Dose Inhaler', category: 'Dosage Form' },
  { id: 'mdp-medrol-dose-pack', code: 'MDP', meaning: 'Medrol Dose Pack', category: 'Drug Name' },
  { id: 'meq-milliequivalent', code: 'MEQ', meaning: 'Milliequivalent', category: 'Unit' },
  { id: 'mag-magnesium', code: 'MAG', meaning: 'Magnesium', category: 'Drug Name' },
  { id: 'mg-milligram', code: 'MG', meaning: 'Milligram', category: 'Unit' },
  { id: 'mg-dl-milligrams-per-deciliter', code: 'MG/DL', meaning: 'Milligrams Per Deciliter Of Blood', category: 'Unit' },
  { id: 'ml-milliliter', code: 'ML', meaning: 'Milliliter', category: 'Unit' },
  { id: 'mm-hg-millimeters-of-mercury', code: 'MM HG', meaning: 'Millimeters Of Mercury', category: 'Unit' },
  { id: 'mtx-methotrexate', code: 'MTX', meaning: 'Methotrexate', category: 'Drug Name' },
  { id: 'mvi-multivitamins', code: 'MVI', meaning: 'Multi-Vitamins Or Multiple Vitamins', category: 'Drug Name' },
  { id: 'n-a-not-available', code: 'N/A', meaning: 'Not Available', category: 'Medical Term' },
  { id: 'n-v-nausea-and-vomiting', code: 'N/V', meaning: 'Nausea And Vomiting', category: 'Symptom' },
  { id: 'na-nausea', code: 'NA', meaning: 'Nausea', category: 'Symptom' },
  { id: 'nacl-sodium-chloride', code: 'NACL', meaning: 'Sodium Chloride', category: 'Drug Name' },
  { id: 'nahco3-sodium-bicarbonate', code: 'NAHCO3', meaning: 'Sodium Bicarbonate', category: 'Drug Name' },
  { id: 'ndc-national-drug-code', code: 'NDC', meaning: 'National Drug Code', category: 'Medical Term' },
  { id: 'neb-nebulizer', code: 'NEB', meaning: 'Nebulizer', category: 'Dosage Form' },
  { id: 'no-number', code: 'NO', meaning: 'Number', category: 'Measurement' },
  { id: 'nos-numbers', code: 'NOS', meaning: 'Numbers', category: 'Measurement' },
  { id: 'noct-night', code: 'NOCT', meaning: 'Night; At Night', category: 'Timing' },
  { id: 'nph-n-insulin', code: 'NPH', meaning: 'N Insulin (Humulin N Or Novolin N)', category: 'Drug Name' },
  { id: 'npi-national-provider-identifier', code: 'NPI', meaning: 'National Provider Identifier', category: 'Medical Term' },
  { id: 'npo-nothing-by-mouth', code: 'NPO', meaning: 'Nothing By Mouth', category: 'Route' },
  { id: 'nr-no-refill', code: 'NR', meaning: 'No Refill', category: 'Direction' },
  { id: 'nrf-no-refills-authorized', code: 'NRF', meaning: 'No Refills Authorized', category: 'Direction' },
  { id: 'ns-nasal-spray', code: 'NS', meaning: 'Nasal Spray', category: 'Dosage Form' },
  { id: 'ntg-nitroglycerin', code: 'NTG', meaning: 'Nitroglycerin', category: 'Drug Name' },
  { id: 'nv-nausea-vomiting', code: 'NV', meaning: 'Nausea/Vomiting', category: 'Symptom' },
  { id: 'odt-orally-disintegrating-tablet', code: 'ODT', meaning: 'Orally Disintegrating Tablet', category: 'Dosage Form' },
  { id: 'oint-ointment', code: 'OINT', meaning: 'Ointment', category: 'Dosage Form' },
  { id: 'oph-ophthalmic', code: 'OPH', meaning: 'Ophthalmic', category: 'Route' },
  { id: 'opht-ophthalmic-preparation', code: 'OPHT', meaning: 'Ophthalmic Preparation', category: 'Route' },
  { id: 'otc-over-the-counter', code: 'OTC', meaning: 'Over The Counter', category: 'Medical Term' },
  { id: 'oz-ounce', code: 'OZ', meaning: 'Ounce', category: 'Unit' },
  { id: 'pb-phenobarbital', code: 'PB', meaning: 'Phenobarbital', category: 'Drug Name' },
  { id: 'pcn-penicillin', code: 'PCN', meaning: 'Penicillin', category: 'Drug Name' },
  { id: 'pct-percent', code: 'PCT', meaning: 'Percent Or Percentage', category: 'Measurement' },
  { id: 'pd-pediatric-drop', code: 'PD', meaning: 'Pediatric Drop', category: 'Dosage Form' },
  { id: 'ped-pediatric', code: 'PED', meaning: 'Pediatric', category: 'Medical Term' },
  { id: 'peg-polyethylene-glycol', code: 'PEG', meaning: 'Polyethylene Glycol', category: 'Drug Name' },
  { id: 'per-by-or-through', code: 'PER', meaning: 'By Or Through', category: 'Route' },
  { id: 'ph-acidity-measure', code: 'PH', meaning: 'Measure Of Acidity Or Basicity', category: 'Measurement' },
  { id: 'pkd-packaged', code: 'PKD', meaning: 'Packaged', category: 'Dosage Form' },
  { id: 'pkg-package', code: 'PKG', meaning: 'Package', category: 'Dosage Form' },
  { id: 'pkt-packet', code: 'PKT', meaning: 'Packet', category: 'Dosage Form' },
  { id: 'pm-evening', code: 'PM', meaning: 'Evening; In The Evening; After Noon', category: 'Timing' },
  { id: 'pms-premenstrual-syndrome', code: 'PMS', meaning: 'Premenstrual Syndrome', category: 'Symptom' },
  { id: 'pnv-prenatal-vitamins', code: 'PNV', meaning: 'Prenatal Vitamins', category: 'Drug Name' },
  { id: 'pp-postprandial', code: 'PP', meaning: 'Postprandial; After Eating', category: 'Timing' },
  { id: 'pr-per-rectum', code: 'PR', meaning: 'Per Rectum; By Rectum', category: 'Route' },
  { id: 'pse-pseudoephedrine', code: 'PSE', meaning: 'Pseudoephedrine', category: 'Drug Name' },
  { id: 'pt-patient', code: 'PT', meaning: 'Patient', category: 'Medical Term' },
  { id: 'ptu-propylthiouracil', code: 'PTU', meaning: 'Propylthiouracil', category: 'Drug Name' },
  { id: 'qdam-every-day-in-morning', code: 'QDAM', meaning: 'Every Day In The Morning', category: 'Frequency' },
  { id: 'qd-pm-every-day-evening', code: 'QD PM', meaning: 'Every Day In The Evening', category: 'Frequency' },
  { id: 'qh-every-hour', code: 'QH', meaning: 'Every Hour (q.h.)', category: 'Frequency' },
  { id: 'q24h-every-24-hours', code: 'Q24H', meaning: 'Every 24 Hours', category: 'Frequency' },
  { id: 'qhs-every-night-at-bedtime', code: 'QHS', meaning: 'Every Night At Bedtime', category: 'Timing' },
  { id: 'qod-every-other-day', code: 'QOD', meaning: 'Every Other Day', category: 'Frequency' },
  { id: 'q8pm-every-day-at-8pm', code: 'Q8PM', meaning: 'Every Day At 8 P.M.', category: 'Timing' },
  { id: 'qs-quantity-sufficient', code: 'QS', meaning: 'Quantity Sufficient', category: 'Measurement' },
  { id: 'qt-quart', code: 'QT', meaning: 'Quart', category: 'Unit' },
  { id: 'qty-quantity', code: 'QTY', meaning: 'Quantity', category: 'Measurement' },
  { id: 'qw-every-week', code: 'QW', meaning: 'Every Week; Once A Week', category: 'Frequency' },
  { id: 'rf-refill', code: 'RF', meaning: 'Refill', category: 'Direction' },
  { id: 'rx-prescription', code: 'RX', meaning: 'Prescription', category: 'Medical Term' },
  { id: 'sa-sustained-action', code: 'SA', meaning: 'Sustained Action', category: 'Dosage Form' },
  { id: 'sc-subcutaneous', code: 'SC', meaning: 'Subcutaneous; Under The Skin', category: 'Route' },
  { id: 'sig-signa', code: 'SIG', meaning: 'Signa; directions for using a prescription', category: 'Direction' },
  { id: 'smz-tmp-sulfamethoxazole-trimethoprim', code: 'SMZ-TMP', meaning: 'Sulfamethoxazole/Trimethoprim', category: 'Drug Name' },
  { id: 'sob-shortness-of-breath', code: 'SOB', meaning: 'Shortness Of Breath (SOB)', category: 'Symptom' },
  { id: 'sod-sodium', code: 'SOD', meaning: 'Sodium', category: 'Drug Name' },
  { id: 'sol-solution', code: 'SOL', meaning: 'Solution', category: 'Dosage Form' },
  { id: 'sq-subcutaneous-route', code: 'SQ', meaning: 'Subcutaneous Route', category: 'Route' },
  { id: 'sr-sustained-release', code: 'SR', meaning: 'Sustained Release', category: 'Dosage Form' },
  { id: 'subq-subcutaneous-injection-route', code: 'SUBQ', meaning: 'Subcutaneous Injection Route', category: 'Route' },
  { id: 'sup-suppository', code: 'SUP', meaning: 'Suppository Form', category: 'Dosage Form' },
  { id: 'susp-suspension', code: 'SUSP', meaning: 'Suspension', category: 'Dosage Form' },
  { id: 'syr-syrup', code: 'SYR', meaning: 'Syrup', category: 'Dosage Form' },
  { id: 'tac-triamcinolone', code: 'TAC', meaning: 'Triamcinolone', category: 'Drug Name' },
  { id: 'tud-take-as-directed', code: 'TUD', meaning: 'Take As Directed', category: 'Direction' },
  { id: 'tat-until-all-taken', code: 'TAT', meaning: 'Until All Taken', category: 'Direction' },
  { id: 'tbsp-tablespoonful', code: 'TBSP', meaning: 'Tablespoonful', category: 'Measurement' },
  { id: 'tcn-tetracycline', code: 'TCN', meaning: 'Tetracycline', category: 'Drug Name' },
  { id: 'tiw-three-times-a-week', code: 'TIW', meaning: 'Three Times A Week', category: 'Frequency' },
  { id: 'tmp-trimethoprim', code: 'TMP', meaning: 'Trimethoprim', category: 'Drug Name' },
  { id: 'top-topical', code: 'TOP', meaning: 'Topical', category: 'Route' },
  { id: 'tr-timed-release', code: 'TR', meaning: 'Timed-Release', category: 'Dosage Form' },
  { id: 'u-units', code: 'U', meaning: 'Units', category: 'Unit' },
  { id: 'uad-use-as-directed', code: 'UAD', meaning: 'Use As Directed', category: 'Direction' },
  { id: 'uat-use-until-all-taken', code: 'UAT', meaning: 'Use Until All Taken', category: 'Direction' },
  { id: 'ut-dict-as-directed', code: 'UT DICT', meaning: 'As Directed (Latin ut dictum)', category: 'Direction' },
  { id: 'ung-ointment', code: 'UNG', meaning: 'Ointment Dosage Form', category: 'Dosage Form' },
  { id: 'uti-urinary-tract-infection', code: 'UTI', meaning: 'Urinary Tract Infection', category: 'Symptom' },
  { id: 'vag-vaginally', code: 'VAG', meaning: 'Vaginally', category: 'Route' },
  { id: 'w-with', code: 'W/', meaning: 'With (written w/)', category: 'Direction' },
  { id: 'w-o-without', code: 'W/O', meaning: 'Without (written w/o)', category: 'Direction' },
  { id: 'wa-while-awake', code: 'WA', meaning: 'While Awake', category: 'Timing' },
  { id: 'wh-wheezing', code: 'WH', meaning: 'Wheezing', category: 'Symptom' },
  { id: 'wk-week', code: 'WK', meaning: 'Week', category: 'Timing' },
  { id: 'wt-weight', code: 'WT', meaning: 'Weight', category: 'Measurement' },
  { id: 'wz-wheezing-symptom', code: 'WZ', meaning: 'Wheezing Symptom', category: 'Symptom' },
  { id: 'x-times', code: 'X', meaning: 'Times', category: 'Direction' },
  { id: 'x1rf-times-one-refill', code: 'X1RF', meaning: 'Times One Refill', category: 'Direction' },
  { id: 'x3rf-times-three-refills', code: 'X3RF', meaning: 'Times Three Refills', category: 'Direction' },
  { id: 'xl-extra-long', code: 'XL', meaning: 'Extra Long', category: 'Measurement' },
  { id: 'xr-extended-release', code: 'XR', meaning: 'Extended Release', category: 'Dosage Form' },
]
