import type { SigCode } from './types'

export const sigCodeSource = {
  name: 'User-provided SIG code sheet',
  reviewedAt: '2026-06-08',
}

export const sigCodes: SigCode[] = [
  { id: 'pc-after-meals', code: 'PC', meaning: 'After Meals', category: 'Timing' },
  { id: 'apl-applicatorful', code: 'APL', meaning: 'Applicatorful', category: 'Measurement' },
  { id: 'app-apply', code: 'APP', meaning: 'Apply', category: 'Application' },
  { id: 'ar-arthritis', code: 'AR', meaning: 'Arthritis', category: 'Symptom' },
  { id: 'ud-as-directed', code: 'UD', meaning: 'As Directed', category: 'Direction' },
  { id: 'hs-at-bedtime', code: 'HS', meaning: 'At Bedtime', category: 'Timing' },
  { id: 'stat-at-once', code: 'STAT', meaning: 'At Once', category: 'Timing' },
  { id: 'bp-blood-pressure', code: 'BP', meaning: 'Blood Pressure', category: 'Symptom' },
  { id: 'ac-before-meals', code: 'AC', meaning: 'Before Meals', category: 'Timing' },
  { id: 'bm-bowel-movement', code: 'BM', meaning: 'Bowel Movement', category: 'Symptom' },
  { id: 'po-by-mouth', code: 'PO', meaning: 'By Mouth', category: 'Route' },
  { id: 'cap-capsule', code: 'CAP', meaning: 'Capsule', category: 'Dosage Form' },
  { id: 'caps-capsules', code: 'CAPS', meaning: 'Capsules', category: 'Dosage Form' },
  { id: 'ci-circulation', code: 'CI', meaning: 'Circulation', category: 'Symptom' },
  { id: 'con-constipation', code: 'CON', meaning: 'Constipation', category: 'Symptom' },
  { id: 'medcp-consultation-provided-by', code: 'MEDCP', meaning: 'Consultation Provided By', category: 'Administration' },
  { id: 'cr-crush', code: 'CR', meaning: 'Crush', category: 'Administration' },
  { id: 'dy-daily', code: 'DY', meaning: 'Daily', category: 'Frequency' },
  { id: 'd-day', code: 'D', meaning: 'Day', category: 'Timing' },
  { id: 'ds-days', code: 'DS', meaning: 'Days', category: 'Timing' },
  { id: 'di-diarrhea', code: 'DI', meaning: 'Diarrhea', category: 'Symptom' },
  { id: 'dr-drink', code: 'DR', meaning: 'Drink', category: 'Administration' },
  { id: 'gtt-drop', code: 'GTT', meaning: 'Drop', category: 'Dosage Form' },
  { id: 'gtts-drops', code: 'GTTS', meaning: 'Drops', category: 'Dosage Form' },
  { id: 'qd-each-day', code: 'QD', meaning: 'Each Day', category: 'Frequency' },
  { id: 'qpm-each-evening', code: 'QPM', meaning: 'Each Evening', category: 'Timing' },
  { id: 'qam-each-morning', code: 'QAM', meaning: 'Each Morning', category: 'Timing' },
  { id: 'q-every', code: 'Q', meaning: 'Every', category: 'Frequency' },
  { id: 'q1h-every-hour', code: 'Q1H', meaning: 'Every Hour', category: 'Frequency' },
  { id: 'q2d-every-second-day', code: 'Q2D', meaning: 'Every Second Day', category: 'Frequency' },
  { id: 'q2h-every-2-hours', code: 'Q2H', meaning: 'Every 2 Hours', category: 'Frequency' },
  { id: 'q3h-every-3-hours', code: 'Q3H', meaning: 'Every 3 Hours', category: 'Frequency' },
  { id: 'q4h-every-4-hours', code: 'Q4H', meaning: 'Every 4 Hours', category: 'Frequency' },
  { id: 'q6h-every-6-hours', code: 'Q6H', meaning: 'Every 6 Hours', category: 'Frequency' },
  { id: 'q8h-every-8-hours', code: 'Q8H', meaning: 'Every 8 Hours', category: 'Frequency' },
  { id: 'q12h-every-12-hours', code: 'Q12H', meaning: 'Every 12 Hours', category: 'Frequency' },
  { id: 'q2-3h-every-2-3-hours', code: 'Q2-3H', meaning: 'Every 2-3 Hours', category: 'Frequency' },
  { id: 'q2-4h-every-2-4-hours', code: 'Q2-4H', meaning: 'Every 2-4 Hours', category: 'Frequency' },
  { id: 'q4-6h-every-4-6-hours', code: 'Q4-6H', meaning: 'Every 4-6 Hours', category: 'Frequency' },
  { id: 'fe-fever', code: 'FE', meaning: 'Fever', category: 'Symptom' },
  { id: 'fl-fluids', code: 'FL', meaning: 'Fluids', category: 'Administration' },
  { id: 'f-for', code: 'F', meaning: 'For', category: 'Direction' },
  { id: 'qid-four-times-daily', code: 'QID', meaning: 'Four Times Daily', category: 'Frequency' },
  { id: 'g-give', code: 'G', meaning: 'Give', category: 'Administration' },
  { id: 'hd-headache', code: 'HD', meaning: 'Headache', category: 'Symptom' },
  { id: 'hr-heart', code: 'HR', meaning: 'Heart', category: 'Symptom' },
  { id: 'h-hour', code: 'H', meaning: 'Hour', category: 'Timing' },
  { id: 'hrs-hours', code: 'HRS', meaning: 'Hours', category: 'Timing' },
  { id: 'au-in-each-ear', code: 'AU', meaning: 'In Each Ear', category: 'Route' },
  { id: 'ou-in-each-eye', code: 'OU', meaning: 'In Each Eye', category: 'Route' },
  { id: 'ien-in-each-nostril', code: 'IEN', meaning: 'In Each Nostril', category: 'Route' },
  { id: 'al-in-the-left-ear', code: 'AL', meaning: 'In the Left Ear', category: 'Route' },
  { id: 'ad-in-the-right-ear', code: 'AD', meaning: 'In the Right Ear', category: 'Route' },
  { id: 'os-in-the-left-eye', code: 'OS', meaning: 'In the Left Eye', category: 'Route' },
  { id: 'od-in-the-right-eye', code: 'OD', meaning: 'In the Right Eye', category: 'Route' },
  { id: 'inf-inflammation', code: 'INF', meaning: 'Inflammation', category: 'Symptom' },
  { id: 'i-inhale', code: 'I', meaning: 'Inhale', category: 'Route' },
  { id: 'inj-inject', code: 'INJ', meaning: 'Inject', category: 'Route' },
  { id: 'medap-injection-administered-by-pharmacist', code: 'MEDAP', meaning: 'Injection Administered by Pharmacist', category: 'Administration' },
  { id: 'ir-insert', code: 'IR', meaning: 'Insert', category: 'Administration' },
  { id: 'ins-instill', code: 'INS', meaning: 'Instill', category: 'Administration' },
  { id: 'r-into-the-rectum', code: 'R', meaning: 'Into the Rectum', category: 'Route' },
  { id: 'v-into-the-vagina', code: 'V', meaning: 'Into the Vagina', category: 'Route' },
  { id: 'ju-juice', code: 'JU', meaning: 'Juice', category: 'Administration' },
  { id: 'n-night', code: 'N', meaning: 'Night', category: 'Timing' },
  { id: 'ss-one-half', code: 'SS', meaning: 'One Half', category: 'Measurement' },
  { id: 'qbid-one-or-two-times-daily', code: 'QBID', meaning: 'One or Two Times Daily', category: 'Frequency' },
  { id: 'pa-pain', code: 'PA', meaning: 'Pain', category: 'Symptom' },
  { id: 'pl-place', code: 'PL', meaning: 'Place', category: 'Application' },
  { id: 'pf-puffs', code: 'PF', meaning: 'Puffs', category: 'Dosage Form' },
  { id: 'ra-rash', code: 'RA', meaning: 'Rash', category: 'Symptom' },
  { id: 'medra-refer-to-adaptation-form', code: 'MEDRA', meaning: 'Refer to Adaptation Form', category: 'Administration' },
  { id: 'medro-refer-to-opinions-form', code: 'MEDRO', meaning: 'Refer to Opinions Form', category: 'Administration' },
  { id: 'sw-shake-well', code: 'SW', meaning: 'Shake Well', category: 'Administration' },
  { id: 'sb-shortness-of-breath', code: 'SB', meaning: 'Shortness of Breath', category: 'Symptom' },
  { id: 'sp-sparingly', code: 'SP', meaning: 'Sparingly', category: 'Direction' },
  { id: 'supp-suppository', code: 'SUPP', meaning: 'Suppository', category: 'Dosage Form' },
  { id: 'tbl-tablespoon', code: 'TBL', meaning: 'Tablespoon', category: 'Measurement' },
  { id: 'tbls-tablespoonfuls', code: 'TBLS', meaning: 'Tablespoonfuls', category: 'Measurement' },
  { id: 'tab-tablet', code: 'TAB', meaning: 'Tablet', category: 'Dosage Form' },
  { id: 'tabs-tablets', code: 'TABS', meaning: 'Tablets', category: 'Dosage Form' },
  { id: 't-take', code: 'T', meaning: 'Take', category: 'Administration' },
  { id: 'tsp-teaspoon', code: 'TSP', meaning: 'Teaspoon', category: 'Measurement' },
  { id: 'tsps-teaspoonfuls', code: 'TSPS', meaning: 'Teaspoonfuls', category: 'Measurement' },
  { id: 'tqid-three-or-four-times-daily', code: 'TQID', meaning: 'Three or Four Times Daily', category: 'Frequency' },
  { id: 'tid-three-times-daily', code: 'TID', meaning: 'Three Times Daily', category: 'Frequency' },
  { id: 'btid-two-or-three-times-daily', code: 'BTID', meaning: 'Two or Three Times Daily', category: 'Frequency' },
  { id: 'admx-to-a-maximum-of', code: 'ADMX', meaning: 'To a Maximum of', category: 'Direction' },
  { id: 'aa-to-affected-area', code: 'AA', meaning: 'To Affected Area', category: 'Application' },
  { id: 'bid-twice-daily', code: 'BID', meaning: 'Twice Daily', category: 'Frequency' },
  { id: 'sl-under-the-tongue', code: 'SL', meaning: 'Under the Tongue', category: 'Route' },
  { id: 'uf-until-finished', code: 'UF', meaning: 'Until Finished', category: 'Direction' },
  { id: 'aq-water', code: 'AQ', meaning: 'Water', category: 'Administration' },
  { id: 'prn-when-required', code: 'PRN', meaning: 'When Required', category: 'Timing' },
  { id: 'prnf-when-necessary-for', code: 'PRNF', meaning: 'When Necessary For', category: 'Timing' },
  { id: 'c-with', code: 'C', meaning: 'With', category: 'Direction' },
  { id: 'cf-with-food', code: 'CF', meaning: 'With Food', category: 'Timing' },
  { id: 'cc-with-meals', code: 'CC', meaning: 'With Meals', category: 'Timing' },
  { id: 's-without', code: 'S', meaning: 'Without', category: 'Direction' },
]
